### PR TITLE
add controller.publishService setting

### LINKED ISSUE #51: Add a dedicated setting for the "publish-service" argument to the chart
As discussed on [Slack](https://kubernetes.slack.com/archives/C01D8GKKT5H/p1654617776211139),

it would make sense to have a way to set the "publish-service" argument with a key in values.yaml; this option tells the controller where to fetch its public IP from so it can in turn populate the `status.loadBalancer.ingress[].ip` field(s) of the Ingress resource(s) it manages.

This can currently be achieved manually by adding `publish-service: <namespace>/<service>` to `controller.extraArgs` in values.yaml, which is not the greatest workaround because the installation namespace is passed to Helm and the service name is rendered by the chart itself, which means that users must assume some of the rendered output in advance and make it part of the values file itself, rather than having an idempotent option.

Care should be taken to not enable/set `publish-service` by default to not break existing setups, as well as setting up the yaml rendering process in such a way that any already-set value for `publish-service` (by means of specifying it in `controller.extraArgs`) is prioritized and thus preserved over the dedicated setting this issue calls for.

The following is a suggested syntax for the proposed setting, [inspired by how ingress-nginx handles the same issue](https://github.com/kubernetes/ingress-nginx/blob/fb2f00bae5c444b742f42e05eddf80a36dd6b7f8/charts/ingress-nginx/values.yaml#L138).

```yaml
# values.yaml

controller:
  # Allows customization of the source of the IP address or FQDN to report
  # in the ingress status field. If disabled (default), the status field remains 
  # unpopulated. If enabled, it reads the information provided by the service,
  # unless pathOverride is specified.
  publishService:
    # Enable 'publishService' or not
    enabled: false
    # Allows overriding of the publish service to bind to
    # Must be <namespace>/<service_name>
    pathOverride: ""
```

### PR DESCRIPTION
**Pull request by itspngu**
Fixes #51.

If there's anything you'd like to see changed or if I missed something, let me know. The docs would have to be updated seperately.

### CODE REVIEW

**Comment by itspngu** [comment]
@jcmoraisjr sorry for the direct tag if you're busy, just making sure this doesn't get lost. Have you had a chance to review? Happily accepting suggestions.

**Comment by jcmoraisjr** [comment]
Hi, I'm back, sorry the delay.

It seems good. Just out of curiosity, any reason to add the service name as a template instead of the usual `{{- with Values... }} <use dot<.>> {{- else }} <use default> {{- end }}`?

**Comment by itspngu** [comment]
Well, the whole logic around when it does or does not have one effect or the other (to avoid breaking changes) already is more elaborate than I'd like it to be, so it seemed sensible to split that up into

step a) "always define a value for `publish-service` that depends on `pathOverride` being set or not, don't care if it's used"
step b) "use that value and append it to the cmdline, only if conditions are fulfilled"

I suppose the entire `define` block could be wrapped like so (to make the fact that it's not always used obvious):

```tpl
{{- if .Values.controller.publishService.enabled }}
  {{- define "haproxy-ingress.controller.publishServicePath" -}}
    {{- if .Values.controller.publishService.pathOverride }}
      {{- .Values.controller.publishService.pathOverride | trimSuffix "-" }}
    {{- else }}
      {{- printf "%s/%s" "$(POD_NAMESPACE)" (include "haproxy-ingress.fullname" .) | trimSuffix "-" }}
    {{- end }}
  {{- end }}
{{- end }}
```

This is what `_podtemplate.yaml` would look like if it's all in there:

```tpl
{{- if and .Values.controller.publishService.enabled (not (hasKey .Values.controller.extraArgs "publish-service")) }}
  {{- if .Values.controller.publishService.pathOverride }}
        - --publish-service={{- .Values.controller.publishService.pathOverride | trimSuffix "-" }}
  {{- else }}
        - --publish-service={{- printf "%s/%s" "$(POD_NAMESPACE)" (include "haproxy-ingress.fullname" .) | trimSuffix "-" }}
  {{- end }}
{{- end }}
```

I'm not exactly passionate about it, just felt it looked less confusing. Your call :)

**Comment by jcmoraisjr** [comment]
Thanks for sharing. You could make it shorter by changing from `if <var> <use-var>` to `with <var> <use-.>` instead, but even then we'd just changing the place of some complexities. It seems good how it's now.

A final comment that I forgot to ask earlier, it's missing the lines in the readme file. I wonder if people really use the readme as doc instead of the values.yaml file, but we still have it so let's maintain it up to date.

**Comment by itspngu** [comment]
I actually forgot about that, done :)

**Comment by jcmoraisjr** [comment]
Great thanks! Lgtm, merging now.

**Pull request merged**
