### PR TITLE
Add dual-stack Service support

### PR DESCRIPTION
**Pull request by bootc**
This adds support for configuring HAProxy Ingress with a dual-stack Service, and supplies some documentation for making this work.

### CODE REVIEW

**Comment by bootc** [comment]
So far I have only tested this using an IPv4-first dual-stack cluster (that is, my `service-cluster-ip-range` and `cluster-cidr` have the IPv4 CIDR listed before the IPv6 one), but it works.

HAProxy Ingress only uses the backend pods' IPv4 addresses, but that's expected as the `status.podIP` is the IPv4 address (due to the order of the `cluster-cidr` addresses); HAProxy Ingress would have to grow support for the `status.podIPs` field to see all the pod addresses. I have not been brave enough to test a cluster where the IPv6 addresses are listed first, either.

**Comment by jcmoraisjr** [comment]
Hi thanks for the PR!

Please move the Dual Stack Mode section just before the Configuration, and add the new attributes to the configuration table.

**Comment by bootc** [comment]
@jcmoraisjr just pushed an update making those changes. Sorry, not sure how I forgot to add the entries to the table... I blame it on brain fade.

**Comment by jcmoraisjr** [comment]
Thanks for the quick fix and also for the contribution! Merging now.

> forgot to add the entries to the table

No problem at all, maybe you also have the impression (just like me) that people do use `values.yaml` instead as the configuration doc =)

**Pull request merged**
